### ISSUE TITLE
can't find 'Denoiser' in module base.py

### ISSUE THREAD

**Issue by Xfc30** [Logan-Lin/MMTEC#1]
transformer.py:
line 9    from model.base import Encoder, Decoder, Denoiser, TimeEmbed
line 185   class TransformerDenoiser(Denoiser):

However, I can't find 'Denoiser' in module base.py. 

Thanks for your help.

**Comment by kfragkedaki** [comment]
Is there an update on that?

**Comment by Logan-Lin** [comment]
Apologies for the (extremely) delayed reply. 

Recently I have reformatted the codes and tested them to ensure that the whole framework can be run without throwing exceptions (following the instructions in readme). Hope you will find them helpful.
