### ISSUE TITLE
data.py

### ISSUE THREAD

**Issue by slzhou-xy** [Logan-Lin/MMTEC#2]
你看看你这个small data能跑你的预处理吗？能放个预处理后的数据吗？

**Comment by Logan-Lin** [comment]
Apologies for the (extremely) delayed reply.

Previously, there are some bugs in the `data.py`. Recently I have reformatted the codes and tested them to ensure that the whole framework can be run without throwing exceptions (following the instructions in readme). Hope you will find them helpful.
